image: node:22

stages:
  - build
  - deploy

cache:  # 全局缓存配置（可选）
  key: 
    files:
      - package-lock.json
    prefix: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  cache:
    key: 
      files:
        - package-lock.json
      prefix: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
    policy: push
    when: on_success

pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir public && cp -rf dist/* public
  artifacts:
    paths:
      - public/
  dependencies: []  # 明确不依赖 build 缓存（通过 artifacts 传递 dist）